application: pivotal-pdf
version: 112
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /helloworld
  script: helloworld.py
  
- url: /localTest
  script: pivotal_pdf_input.py 
    
- url: /.*
  script: pivotal_pdf_input.py  
