application: pivotalpdf
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /helloworld
  script: helloworld.py
  
- url: /testpdf
  script: testpdf.py
    
- url: /.*
  script: pivotal_pdf_input.py  
