application: pivotal-pdf
version: 114
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /helloworld
  script: helloworld.py
  
- url: /localTest
  script: pivotal_pdf_input.py 
    
- url: /.*
  script: pivotal_pdf_input.py  
